environment:
  MYSQL_DATABASE: test
  MYSQL_HOST: localhost
  MYSQL_USER: root
  MYSQL_PASSWORD: Password12!
  MYSQL_PATH: C:\Program Files\MySQL\MySQL Server 5.7
  LINT: 0

  matrix:
    - nodejs_version: "7.6.0"
    - nodejs_version: "8.11.1"
    - nodejs_version: "10.1.0"

services:
  - mysql

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

before_test:
  - SET PATH=%MYSQL_PATH%\bin;%PATH%
  - mysqladmin --host=%MYSQL_HOST% --user=%MYSQL_USER% --password=%MYSQL_PASSWORD% create %MYSQL_DATABASE%

test_script:
  - mysql --version
  - node --version
  - npm --version
  # run tests
  - npm test

version: "{build}"